#!/usr/bin/env bash

# Get the absolute path of this executable
ORIGDIR=$(pwd)
SELF_PATH=$(cd -P -- "$(dirname -- "$0")" && pwd -P) && SELF_PATH=$SELF_PATH/$(basename -- "$0")

# Resolve symlinks - this is the equivalent of "readlink -f", but also works with non-standard OS X readlink.
while [ -h $SELF_PATH ]; do
    DIR=$(dirname -- "$SELF_PATH")
    SYM=$(readlink $SELF_PATH)
    SELF_PATH=$(cd $DIR && cd $(dirname -- "$SYM") && pwd)/$(basename -- "$SYM")
done
cd "$ORIGDIR"

# Build the path to drush.php.
SCRIPT_PATH=$(dirname $SELF_PATH)/organize.php
[[ $(uname -a) == CYGWIN* ]] && SCRIPT_PATH=$(cygpath -w -a -- "$SCRIPT_PATH")

if [ $1 ] ; then
  DIR=$1
else
  DIR=$ORIGDIR
fi

# We check for a command line (cli) version of php, and if found use that.
/usr/bin/env php-cli -v &> /dev/null
if [ "$?" = 0 ] ; then
  /usr/bin/env php-cli $SCRIPT_PATH $DIR "$@"
else
  # Alternatively we run with straight php, which works on most other systems.
  /usr/bin/env php -n $SCRIPT_PATH $DIR "$@"
fi